--TABLA DETALLE_ATENCIONES
SELECT 
RUT_MEDICO,
PERIODO, 
TOTAL_ATENCIONES, 
COSTO_ATENCIONES, 
TASA_APORTE_PERIODO 
FROM DETALLE_ATENCIONES;


--TABLA RESUMEN_MEDICO
SELECT 
RUT_MEDICO, 
NOMBRE_COMPLETO, 
NOMBRE_CARGO, 
NOMBRE_UNIDAD, 
SUELDO_BASE, 
DIFERENCIA_CARGO, 
SOBRE_PROMEDIO 
FROM RESUMEN_MEDICO; 


