-- La siguiente linea la debes descomentar SI Y SOLO SI tienes instalado el Oracle 18c
--ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER EA1_1_MDY_FOL IDENTIFIED BY duoc
--DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER EA1_1_MDY_FOL QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO EA1_1_MDY_FOL;
GRANT "CONNECT" TO EA1_1_MDY_FOL;
ALTER USER EA1_1_MDY_FOL DEFAULT ROLE "RESOURCE","CONNECT";
