CREATE TABLE GAME_STUDIO_APP_CATEGORIA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(100) NOT NULL
);

CREATE TABLE GAME_STUDIO_APP_JUEGO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_juego VARCHAR2(100) NOT NULL,
    categoria_juego_id NUMBER NOT NULL,
    precio_juego NUMBER(10, 2) NOT NULL,
    descripcion_juego CLOB,
    imagen_juego VARCHAR2(255),
    CONSTRAINT fk_categoria_juego FOREIGN KEY (categoria_juego_id)
        REFERENCES GAME_STUDIO_APP_CATEGORIA(id) ON DELETE CASCADE
);


INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('accion');
INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('terror');
INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('carreras');
INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('mundo_abierto');
INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('free_to_play');
INSERT INTO GAME_STUDIO_APP_CATEGORIA (nombre_categoria) VALUES ('supervivencia');

INSERT INTO GAME_STUDIO_APP_JUEGO (titulo_juego, categoria_juego_id, precio_juego, descripcion_juego, imagen_juego)
VALUES (
    'Mario Kart', 
    (SELECT id FROM GAME_STUDIO_APP_CATEGORIA WHERE nombre_categoria = 'carreras'),
    39000,
    'Mario Kart es una serie de videojuegos de carreras que es desarrollada y publicada por Nintendo. La serie es conocida por su jugabilidad arcade, la cual se enfoca en la jugabilidad y el juego competitivo. Los jugadores pueden elegir entre una variedad de personajes de la franquicia de Mario, cada uno con sus propias habilidades y vehículos.',
    'imagenes/mario_kart.jpeg'
);

INSERT INTO GAME_STUDIO_APP_JUEGO (titulo_juego, categoria_juego_id, precio_juego, descripcion_juego, imagen_juego)
VALUES (
    'Roblox', 
    (SELECT id FROM GAME_STUDIO_APP_CATEGORIA WHERE nombre_categoria = 'mundo_abierto'),
    23000,
    'Roblox es una plataforma de juegos en línea lanzada en 2006 que permite a los usuarios crear, compartir y jugar en mundos virtuales generados por otros usuarios. Con una gran comunidad y una amplia variedad de juegos creados por usuarios, Roblox ofrece experiencias interactivas que van desde juegos de rol y simulaciones hasta aventuras y minijuegos. Es especialmente popular entre los jóvenes, gracias a su enfoque en la creatividad, la socialización y la libertad para desarrollar y explorar una amplia gama de contenidos.',
    'imagenes/roblox.png'
);


INSERT INTO GAME_STUDIO_APP_JUEGO (titulo_juego, categoria_juego_id, precio_juego, descripcion_juego, imagen_juego)
VALUES (
    'Los Sims 4', 
    (SELECT id FROM GAME_STUDIO_APP_CATEGORIA WHERE nombre_categoria = 'free_to_play'),
    26600,
    'Los Sims 4 es un popular juego de simulación de vida lanzado en 2014 para PC y consolas. En este juego, los jugadores crean y controlan personajes virtuales, llamados Sims, guiándolos a través de sus vidas cotidianas, desde actividades básicas hasta la construcción de relaciones, carreras y hogares. Con una gran cantidad de contenido personalizado y expansiones, Los Sims 4 ofrece una experiencia abierta y creativa, donde los jugadores pueden diseñar su propio mundo y contar historias únicas, haciendo de cada partida una experiencia diferente.',
    'imagenes/sims4.png'
);


INSERT INTO GAME_STUDIO_APP_JUEGO (titulo_juego, categoria_juego_id, precio_juego, descripcion_juego, imagen_juego)
VALUES (
    'Resident Evil 4', 
    (SELECT id FROM GAME_STUDIO_APP_CATEGORIA WHERE nombre_categoria = 'terror'),
    26600,
    'Resident Evil 4 (estilizado como 4 resident evil)— conocido en Japón como Biohazard 4 
                (estilizado como 4 biohazard) (バイオハザード Baiohazādo Fō )— es un videojuego de acción-aventura de disparos en tercera persona 
                perteneciente al subgénero de terror y supervivencia desarrollado por Capcom Production Studio 4.',
    'imagenes/resident_evil_4.png'
);




COMMIT;
