CREATE USER E1MDY_FOL 
IDENTIFIED BY "S.4_duoc"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
GRANT CREATE SESSION TO E1MDY_FOL;
-- QUOTAS
ALTER USER E1MDY_FOL QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO E1MDY_FOL;
GRANT "CONNECT" TO E1MDY_FOL;
ALTER USER E1MDY_FOL DEFAULT ROLE "RESOURCE","CONNECT";

