# Generated by Django 5.1 on 2024-09-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_studio_app', '0002_categoria_carrito_itemcarrito_juego_metodopago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='modificarperfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='ModificarPerfil',
        ),
    ]
