# Generated by Django 5.1.1 on 2024-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_studio_app', '0003_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
