# Generated by Django 5.1 on 2024-09-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_studio_app', '0004_alter_games_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
    ]
